version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: detran
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:docker-entrypoint-initdb.d

  #backend:
  #  build: ./backend
  #  container_name: backend_detran
  #  restart: always
  #  depends_on:
  #    - mysql
  #  environment:
  #    DB_HOST: mysql
  #    DB_USER: root
  #    DB_PASSWORD: password
  #    DB_NAME: detran
  #  ports:
  #    - "3000:3000"

  # frontend:
  #  build: ./app/frontend
  #  container_name: frontend_container
  #  restart: always
  #  depends_on:
  #    - backend
  #  ports:
  #    - "4200:80"

volumes:
  mysql_data:
